import { useState, useEffect } from 'react';
import { Dialog, DialogFooter, PrimaryButton, DefaultButton } from '@fluentui/react';


const config_rosu = {
  // message: import.meta.env.CUSTOM_DISCLAIMER || 
  //   "Models can make mistakes; it is the user's responsibility to verify the answers.",
  message: 'We continuously enhance the Automated AI Assistance function, which uses Generative Artificial Intelligence (GAI) for information retrieval and content generation. This tool is intended for official use only and requires human oversight. Specifically, as responses generated by this Chatbot may be incomplete or inaccurate, all AI-generated content must be reviewed by a human for accuracy before use. For clarification on any of the AI-generated content, consult the designated subject matter expert or point of contact. All interactions with this tool are logged for security, compliance, and quality assurance. Users must not input classified information or sensitive unclassified information, including but not limited to proprietary or personally identifiable information (PII). For more information on use of GAI in FAA, see FAA Notice 1370.51 Use of Generative AI Tools and Services.'
};

console.log('test:' + import.meta.env.CUSTOM_DISCLAIMER)

export const MessageDialog = () => {
  const [isDialogVisible, setIsDialogVisible] = useState(false);

  useEffect(() => {

    const accepted = sessionStorage.getItem('rosu_Accepted');
    if (!accepted) {
      setIsDialogVisible(true);
    }
  }, []);

  const rosu_Accept = () => {
    sessionStorage.setItem('rosu_Accepted', 'true');
    setIsDialogVisible(false);
  };

  const rosu_deny = () => {
    alert("The terms of use must be accepted.");
    setIsDialogVisible(true);
  };

  return (
    <>
      <Dialog
        hidden={!isDialogVisible}
        onDismiss={() => {}}
        dialogContentProps={{
          title: "Rules of System Use",
          subText: config_rosu.message,
        }}

        styles={{
          main: {
            selectors: {
              ['@media (min-width: 480px)']: {
                width: 800,
                minWidth: 800,
                maxWidth: '1000px'
              }
            }
          }
        }}
      >
        <DialogFooter>
          <PrimaryButton onClick={rosu_Accept} text="Accept" />
          <DefaultButton onClick={rosu_deny} text="Deny" />
        </DialogFooter>
      </Dialog>
    </>
  );
};